src/components/Auth/components/Login.tsx, src/components/Auth/components/SignUp.tsx, src/components/Control/assets/styles/login.css, src/components/Control/assets/styles/signUp.css
Se reestablece los archivos del SignUp.tsx, el signUp.css, los cabios en login.tsx y el estilo del mismo
=> Cambios en diseño y redireccionamiento

package-lock.json, package.json, src/Api/axiosConfig.ts, src/components/Auth/components/Login.tsx, src/components/Middlewares/authTokenMiddlewar.tsx, src/components/NavBar/components/NavBar.tsx, src/components/Routes/AppRoutes.tsx, src/redux/userSlices.ts
Se restringio la vista de procesar pago por medio del token, porfavor de revisar cambios y ver que este bien la funcionalidad
=> Logica de token

src/components/Cart/Components/CartItem.tsx, src/components/Cart/Components/ShopCart.tsx, src/components/Productos/components/SectionProducts.tsx, src/controllers/cartController.ts, src/models/cartModel.ts, src/redux/cartSlice.ts, src/redux/productosSlice.ts, src/redux/store.ts
se crea el redux para visualizar los productos seleccionados por el usuario al carrito
=> Features/view cart 

.gitignore, src/components/Productos/assets/styles/CardProduct.css, src/components/Productos/components/CardProduct.tsx, src/components/Productos/interfaces/Product.ts, src/models/productModel.ts, src/redux/productosSlice.ts
En este commit se corrigieron algunos estilos de el card de producto agregandole el addcarrito
=> Fix-card-product-style

src/components/Productos/assets/styles/DetailProduct.css, src/components/Productos/components/DetailProduct.tsx, src/components/Routes/AppRoutes.tsx
Listo, usa la interface y espera los parametros de la interface de product para que se pueda pbloar se deja la maquetación lista, faltaria nada mas qeu se consuma porque en si ya espera los datos como se mandan desde la API
=> Features-detail-products

.gitignore, src/components/Auth/components/Login.tsx, src/components/Cart/Components/ShopCart.tsx, src/components/Productos/components/CardProduct.tsx, src/components/Productos/components/addToCartOut.ts, src/components/Productos/interfaces/Product.ts, src/redux/userSlices.ts
Actualizado .gitignore, refactorizado los componentes Cart y CardProduct, modificado la interfaz Product y añadido el reducer setUserIdOnly a userSlices.
=> cambios en el carrito 

src/components/Home/assets/styles/CarouselClientes.css, src/components/Home/assets/styles/CarouselProducts.css, src/components/Home/assets/styles/CarouselPromotions.css, src/components/Home/assets/styles/Home.css, src/components/Home/components/CarouselClientes.tsx, src/components/Home/components/CarouselProducts.tsx, src/components/Home/components/SectionHome.tsx, src/components/NavBar/assets/styles/NavBar.css, src/index.css
Se realizaron algunas modificaciones y se tiene una mejor responsividad, faltando unicamente detallitos de imagenes y de verificar que la responsividad para pantllas gigantes funcione
=> fix style de home

package-lock.json, package.json, src/components/ContactUs/assets/styles/SectionContactUs.css, src/components/ContactUs/components/SectionContactUs.tsx, src/components/NavBar/assets/styles/NavBar.css
se reparan los estilos, y la responsividad de la parte de contactanos, para uqe esta se meustre de una mejor manera responsiva, y ademas, se corrigieron algunos detalles en la parte del formulario. de igual forma se agrego validaciones con zod, revisar antes de aceptar por favor
=> fix contact us

src/components/Auth/components/Login.tsx, src/components/Auth/components/UserProfile.tsx, src/components/NavBar/components/NavBar.tsx, src/components/Productos/components/CardProduct.tsx, src/redux/userSlices.ts
Se cambia el archivo del carProducto debido a que causo conflicto el que esta en el merge, además de ello se sube mis cambios de la vista Mi CUENTA los datos del usuario ya se pueden editar e igual la imagen se puede modfiicar
=> Actualización

.gitignore, package-lock.json, package.json, src/components/Auth/components/Login.tsx, src/components/Auth/components/UserProfile.tsx, src/components/ContactUs/assets/styles/SectionContactUs.css, src/components/ContactUs/components/SectionContactUs.tsx, src/components/NavBar/components/NavBar.tsx, src/components/Productos/assets/styles/CardProduct.css, src/components/Productos/components/CardProduct.tsx, src/models/productModel.ts, src/redux/productosSlice.ts, src/redux/userSlices.ts
Realicen una revisión del codigo, si no estoy mal, se conservaron los commit anteriores e incluso se soluciono
=> Features user profile

.gitignore, package-lock.json, package.json, src/components/Auth/components/Login.tsx, src/components/Auth/components/UserProfile.tsx, src/components/ContactUs/assets/styles/SectionContactUs.css, src/components/ContactUs/components/SectionContactUs.tsx, src/components/NavBar/components/NavBar.tsx, src/components/Productos/assets/styles/CardProduct.css, src/components/Productos/components/CardProduct.tsx, src/models/productModel.ts, src/redux/productosSlice.ts, src/redux/userSlices.ts
* Se realiza la autenticación del token (#14)
* Fix-card-product-style (#15)
En este commit se corrigieron algunos estilos de el card de producto agregandole el addcarrito
* Se realiza los componentes para que la imagen puese ser mandada al backend
* Funcionalidad de la imagen en perfil completa
* Se ajusta la función handleSave para que pueda mandar los datos del form al backend
* fix contact us
se reparan los estilos, y la responsividad de la parte de contactanos, para uqe esta se meustre de una mejor manera responsiva, y ademas, se corrigieron algunos detalles en la parte del formulario. de igual forma se agrego validaciones con zod
* Se realiza las modificaciones para que pueda ser actualizado los datos del usuario y la imagen al mismo tiempo o separado
* Se corrige problema del …
=> Actualización 

src/components/Auth/components/Login.tsx
Se agregan los cambios para la logueo desde el main
=> Cambios de validación de datos

src/components/Auth/components/Login.tsx, src/components/Cart/Components/ShopCart.tsx, src/components/Cart/Components/interfaces/cartInterface.ts, src/components/NavBar/components/NavBar.tsx, src/components/Productos/components/CardProduct.tsx, src/controllers/cartController.ts, src/models/cartModel.ts, src/redux/cartSlice.ts
=> logica para ver carrito

src/components/Home/assets/styles/CarouselPromotions.css, src/components/Home/assets/styles/Home.css, src/components/Home/components/CarouselPromotions.tsx, src/components/Home/components/SectionHome.tsx, src/components/NavBar/components/NavBar.tsx
faltando mejorar la responsividad de los componentes que se renderizan dentro
=> fix de home provicional

src/components/Auth/assets/login.css, src/components/Auth/components/Login.tsx
Se realiza los cambios del diseño del login y la responsividad
=> Diseño del login

src/components/Home/assets/styles/CarouselClientes.css, src/components/Home/assets/styles/CarouselPromotions.css, src/components/Home/assets/styles/Home.css
la repsonsividad y diseño ya estna listas totalmente, fue probada y si funciono correctamente
=> fix de home-responsividad

src/components/Productos/components/CardProduct.tsx, src/controllers/cartController.ts, src/models/productModel.ts
=> Fixedcardproduct

src/components/Auth/components/Login.tsx
se maneja funcionalidad para poder agregar los productos a la bd desde el localstorage
=> Se agregó funcionalidad para agregar productos desde local

src/components/Cart/Components/ShopCart.tsx, src/components/Cart/assets/styles/ShoppingCart.css, src/models/cartModel.ts
se crea logica para poder vaciar el carrito
=> Se agregó funcionalidad para vaciar el carrito

package-lock.json, package.json, src/components/Auth/components/UserProfile.tsx, src/components/NavBar/components/NavBar.tsx, src/components/Productos/assets/styles/CardProduct.css, src/components/Productos/assets/styles/DetailProduct.css, src/components/Productos/assets/styles/SectionProduct.css, src/components/Productos/assets/styles/SkeletonProductLoader.css, src/components/Productos/components/CardProduct.tsx, src/components/Productos/components/DetailProduct.tsx, src/components/Productos/components/SectionProducts.tsx, src/components/Productos/components/SkeletonProducto.tsx, src/components/Routes/AppRoutes.tsx, src/redux/productDetailsSlice.ts, src/redux/productosSlice.ts, src/redux/store.ts
Se corrigio la parte del fragmento que fue eliminado y sigue teniendo sus funciones sin ningún problema
=> Fix cardprod and detail

src/components/Cart/Components/ShopCart.tsx, src/components/Cart/assets/styles/ShoppingCart.css
En este commit se mejoraron los estilos para un estilo más limpio y poco mas ordenado, ademas se añadió la parte del código de descuento y funciona correctamente
=> FIx de estilos and features  --- IMPORTANTE VALIDAR ANTES --

package-lock.json, package.json, src/components/AboutUs/assets/styles/SectionAboutUs.css, src/components/AboutUs/components/SectionAboutUs.tsx, src/components/Cart/Components/ShopCart.tsx, src/components/Cart/assets/styles/ShoppingCart.css, src/components/Compras/assets/shopping.css, src/components/Compras/components/shopping_section.tsx, src/components/Control/components/Footer.tsx, src/components/Home/assets/styles/CarouselCategories.css, src/components/Home/assets/styles/CarouselProducts.css, src/components/Home/assets/styles/CarouselReviews.css, src/components/Home/assets/styles/Home.css, src/components/Home/components/CarouselCategories.tsx, src/components/Home/components/CarouselProducts.tsx, src/components/Home/components/SectionHome.tsx, src/components/Productos/components/SectionProducts.tsx
Merge con main para actualizar la rama Main, verificar antes
=> Fix features main dic

src/components/Productos/components/SectionProducts.tsx
final se agrego mas funcionalidad para que abarque todos los productos
=> fix de filtros
